---
# tasks file for nginx
- name: Install nginx
  become: yes
  package:
    name: nginx
    state: present
- name: Copy nginx config
  become: yes
  template:
    src: ./templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: nginx
- name: Enable and start nginx
  become: yes
  service:
    name: nginx
    enabled: yes
    state: started