---
- name: Query instance info
  ec2_instance:
    region: "{{ aws_region }}"
    filters:
      tag:Name: "{{ ec2_instance_name }}"
      instance-state-name: running
  register: ec2_data
- debug:
    msg: "Public IP: {{ ec2_data.instances[0].network_interfaces[0].association.public_ip }}"