---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Setup AWS
      import_role:
        name: aws
      tags:
        - provision
    - name: Cleanup AWS
      import_role:
        name: aws
        tasks_from: cleanup
      tags:
        - cleanup
        - never
    - name: Info about provisioned AWS structure
      import_role:
        name: aws
        tasks_from: info
      tags:
        - info
        - never
    - name: refresh Ansible inventory
      meta: refresh_inventory
      tags:
        - always
  vars:
    secgroup_ssh_allowed_instructor_cidr: 24.80.141.154/32
# - hosts: aws_ec2
#   gather_facts: false
#   tasks:
#     - name: Wait for ec2 to become ssh reachable
#       wait_for_connection:
#         timeout: 60
#       tags:
#         - always
#     - name: Deoploy App
#       import_role:
#         name: todoapp
#       tags:
#         - deployment
#     - name: Info about Nginx service
#       import_role:
#         name: nginx
#         tasks_from: info
#       tags:
#         - info
#         - never
#     - name: Info about todoapp service
#       import_role:
#         name: todoapp_service_info
#         tasks_from: info
#       tags:
#         - info
#         - never
#   vars:
#     todo_user: todoapp
    