---
# tasks file for todoapp_service
- name: Clone app repo
  become: yes
  git:
    repo: https://github.com/timoguic/ACIT4640-todo-app.git
    force: yes
    dest: /home/{{todo_user}}/app
- name: Change database configuration
  become: yes
  replace:
    path: /home/{{todo_user}}/app/config/database.js
    regexp: 'CHANGEME'
    replace: 'acit4640'
- name: Install npm packages based on package.json.
  become: yes
  npm:
    path: /home/{{todo_user}}/app
- name: Copy todoapp.service
  become: yes
  template:
    src: ./templates/todoapp.service.j2
    dest: /etc/systemd/system/todoapp.service
- name: Enable and start todoapp.service
  become: yes
  systemd: 
    state: started
    enabled: yes
    name: todoapp
    daemon_reload: yes