---
#handlers file for mongodb
- name: Copy mongodb archive
  become: yes
  copy:
    src: ./files/restful_blog_app
    dest: /home/blogapp_installation/setup/
- name: Restore mongo data
  command: mongorestore --noIndexRestore -d restful_blog_app /home/blogapp_installation/setup/restful_blog_app